// Date: 05/10/2014 15:45:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package tardis.client.renderer.model.console;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SpecialLeverModel extends ModelBase
{
	//fields
		ModelRenderer Shape2;
		ModelRenderer Shape3;
		ModelRenderer Shape4;
		ModelRenderer Shape5;
	
	public SpecialLeverModel()
	{
		textureWidth = 32;
		textureHeight = 16;
		
		Shape2 = new ModelRenderer(this, 12, 0);
		Shape2.addBox(0F, 0F, 0F, 1, 1, 2);
		Shape2.setRotationPoint(0F, 2F, -2F);
		Shape2.setTextureSize(32, 16);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 18, 0);
		Shape3.addBox(0F, 1F, 0F, 1, 6, 1);
		Shape3.setRotationPoint(0F, -5F, -2F);
		Shape3.setTextureSize(32, 16);
		Shape3.mirror = true;
		setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new ModelRenderer(this, 12, 3);
		Shape4.addBox(0F, 1F, 0F, 1, 1, 1);
		Shape4.setRotationPoint(0F, -5F, -1F);
		Shape4.setTextureSize(32, 16);
		Shape4.mirror = true;
		setRotation(Shape4, 0F, 0F, 0F);
		Shape5 = new ModelRenderer(this, 0, 0);
		Shape5.addBox(-0.5F, -0.5F, -0.5F, 2, 2, 4);
		Shape5.setRotationPoint(0F, -4F, 0F);
		Shape5.setTextureSize(32, 16);
		Shape5.mirror = true;
		setRotation(Shape5, 0F, 0F, 0F);
	}
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
	}

}
