// Date: 25/09/2014 15:44:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package tardis.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class TardisModel extends ModelBase
{
  //fields
    ModelRenderer baseBox;
    ModelRenderer baseSkirting;
    ModelRenderer signOne;
    ModelRenderer signTwo;
    ModelRenderer signThree;
    ModelRenderer signFour;
    ModelRenderer pilllarOne;
    ModelRenderer pillarTwo;
    ModelRenderer pillarThree;
    ModelRenderer pillarFour;
    ModelRenderer topWide;
    ModelRenderer topNarrow;
    ModelRenderer lightBox;
    ModelRenderer doorStrip;
  
  public TardisModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      baseBox = new ModelRenderer(this, 0, 0);
      baseBox.addBox(-8F, 0F, -8F, 16, 32, 16);
      baseBox.setRotationPoint(0F, -8F, 0F);
      baseBox.setTextureSize(128, 128);
      baseBox.mirror = true;
      setRotation(baseBox, 0F, 0F, 0F);
      baseSkirting = new ModelRenderer(this, 44, 34);
      baseSkirting.addBox(-10F, 0F, -10F, 20, 2, 20);
      baseSkirting.setRotationPoint(0F, 22F, 0F);
      baseSkirting.setTextureSize(128, 128);
      baseSkirting.mirror = true;
      setRotation(baseSkirting, 0F, 0F, 0F);
      signOne = new ModelRenderer(this, 0, 48);
      signOne.addBox(-8F, 0F, -10F, 16, 3, 2);
      signOne.setRotationPoint(0F, -7.9F, 0F);
      signOne.setTextureSize(128, 128);
      signOne.mirror = true;
      setRotation(signOne, 0F, 0F, 0F);
      signTwo = new ModelRenderer(this, 0, 48);
      signTwo.addBox(-8F, 0F, -10F, 16, 3, 2);
      signTwo.setRotationPoint(0F, -7.9F, 0F);
      signTwo.setTextureSize(128, 128);
      signTwo.mirror = true;
      setRotation(signTwo, 0F, 1.570796F, 0F);
      signThree = new ModelRenderer(this, 0, 48);
      signThree.addBox(-8F, 0F, -10F, 16, 3, 2);
      signThree.setRotationPoint(0F, -7.9F, 0F);
      signThree.setTextureSize(128, 128);
      signThree.mirror = true;
      setRotation(signThree, 0F, 3.141593F, 0F);
      signFour = new ModelRenderer(this, 0, 48);
      signFour.addBox(-8F, 0F, -10F, 16, 3, 2);
      signFour.setRotationPoint(0F, -7.9F, 0F);
      signFour.setTextureSize(128, 128);
      signFour.mirror = true;
      setRotation(signFour, 0F, 4.712389F, 0F);
      pilllarOne = new ModelRenderer(this, 64, 0);
      pilllarOne.addBox(7F, 0F, 7F, 2, 32, 2);
      pilllarOne.setRotationPoint(0F, -8F, 0F);
      pilllarOne.setTextureSize(128, 128);
      pilllarOne.mirror = true;
      setRotation(pilllarOne, 0F, 0F, 0F);
      pillarTwo = new ModelRenderer(this, 64, 0);
      pillarTwo.addBox(7F, 0F, 7F, 2, 32, 2);
      pillarTwo.setRotationPoint(0F, -8F, 0F);
      pillarTwo.setTextureSize(128, 128);
      pillarTwo.mirror = true;
      setRotation(pillarTwo, 0F, 1.570796F, 0F);
      pillarThree = new ModelRenderer(this, 64, 0);
      pillarThree.addBox(7F, 0F, 7F, 2, 32, 2);
      pillarThree.setRotationPoint(0F, -8F, 0F);
      pillarThree.setTextureSize(128, 128);
      pillarThree.mirror = true;
      setRotation(pillarThree, 0F, 3.141593F, 0F);
      pillarFour = new ModelRenderer(this, 64, 0);
      pillarFour.addBox(7F, 0F, 7F, 2, 32, 2);
      pillarFour.setRotationPoint(0F, -8F, 0F);
      pillarFour.setTextureSize(128, 128);
      pillarFour.mirror = true;
      setRotation(pillarFour, 0F, 4.712389F, 0F);
      topWide = new ModelRenderer(this, 59, 56);
      topWide.addBox(-8F, 0F, -8F, 16, 1, 16);
      topWide.setRotationPoint(0F, -9F, 0F);
      topWide.setTextureSize(128, 128);
      topWide.mirror = true;
      setRotation(topWide, 0F, 0F, 0F);
      topNarrow = new ModelRenderer(this, 25, 56);
      topNarrow.addBox(-6F, 0F, -6F, 12, 2, 12);
      topNarrow.setRotationPoint(0F, -11F, 0F);
      topNarrow.setTextureSize(128, 128);
      topNarrow.mirror = true;
      setRotation(topNarrow, 0F, 0F, 0F);
      lightBox = new ModelRenderer(this, 0, 54);
      lightBox.addBox(-1F, 0F, -1F, 2, 3, 2);
      lightBox.setRotationPoint(0F, -14F, 0F);
      lightBox.setTextureSize(128, 128);
      lightBox.mirror = true;
      setRotation(lightBox, 0F, 0F, 0F);
      doorStrip = new ModelRenderer(this, 72, 0);
      doorStrip.addBox(-0.5F, 0F, -0.5F, 1, 32, 1);
      doorStrip.setRotationPoint(0F, -8F, -8F);
      doorStrip.setTextureSize(128, 128);
      doorStrip.mirror = true;
      setRotation(doorStrip, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    baseBox.render(f5);
    baseSkirting.render(f5);
    signOne.render(f5);
    signTwo.render(f5);
    signThree.render(f5);
    signFour.render(f5);
    pilllarOne.render(f5);
    pillarTwo.render(f5);
    pillarThree.render(f5);
    pillarFour.render(f5);
    topWide.render(f5);
    topNarrow.render(f5);
    lightBox.render(f5);
    doorStrip.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
